### ISSUE TITLE
Qt 6.X not working

### ISSUE THREAD

**Issue by TomVer99** [itsmepvr/anki-reset-profile#1]
Hi there,

I just tried using this add-on with the Qt6 version of Anki, and it crashed on startup.

My Anki version info:
```
Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
```

I checked if the add-on had any updates and it did not so I am sure that I was using the most recent version.

The Debug Info:
```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading Reset Profile:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Tom\AppData\Roaming\Anki2\addons21\1976367957\__init__.py", line 16, in <module>
    from . import reset_profile
  File "C:\Users\Tom\AppData\Roaming\Anki2\addons21\1976367957\reset_profile.py", line 6, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by itsmepvr** [comment]
Yes, this is an issue with the Qt version after the latest Anki update to Qt6. Will be updating soon.

**Comment by itsmepvr** [comment]
Addon updated for Anki 23*.
